name: Automated Data Preprocessing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn

      - name: Run automated preprocessing
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn

      - name: Upload preprocessed dataset artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bank_customer_churn_preprocessed
          path: preprocessing/bank_customer_churn_preprocessing/bank_customer_churn_preprocessed.csv